# Generated by Django 5.0.3 on 2024-03-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediatheque', '0002_alter_emprunteur_bloque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunteur',
            name='id_emprunteur',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
