# Generated by Django 5.0.3 on 2024-03-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediatheque', '0003_alter_emprunteur_id_emprunteur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cd',
            name='id_emprunteur',
        ),
        migrations.RemoveField(
            model_name='dvd',
            name='id_emprunteur',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='id_emprunteur',
        ),
        migrations.AddField(
            model_name='livre',
            name='emprunteurs',
            field=models.ManyToManyField(related_name='livres_empruntes', to='mediatheque.emprunteur'),
        ),
    ]
