# Generated by Django 5.0.3 on 2024-03-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediatheque', '0004_remove_cd_id_emprunteur_remove_dvd_id_emprunteur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='dateEmprunt',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='livre',
            name='disponible',
            field=models.BooleanField(null=True),
        ),
    ]
