# Generated by Django 5.0.3 on 2024-03-11 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediatheque', '0005_alter_livre_dateemprunt_alter_livre_disponible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livre',
            name='dateEmprunt',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='emprunteurs',
        ),
        migrations.CreateModel(
            name='Emprunteur_Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateEmprunt', models.DateField(null=True)),
                ('disponible', models.BooleanField(null=True)),
                ('emprunteurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediatheque.emprunteur')),
            ],
        ),
    ]
