# Generated by Django 5.0.3 on 2024-03-11 19:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediatheque', '0006_remove_livre_dateemprunt_remove_livre_disponible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunteur_livre',
            name='livre',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mediatheque.livre'),
        ),
        migrations.AlterField(
            model_name='emprunteur_livre',
            name='dateEmprunt',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
