# Generated by Django 5.0.3 on 2024-03-12 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediatheque', '0007_emprunteur_livre_livre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dvd',
            name='dateEmprunt',
        ),
        migrations.RemoveField(
            model_name='dvd',
            name='disponible',
        ),
        migrations.CreateModel(
            name='Emprunteur_Dvd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateEmprunt', models.DateField()),
                ('disponible', models.BooleanField()),
                ('dvd', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mediatheque.dvd')),
                ('emprunteurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediatheque.emprunteur')),
            ],
        ),
    ]
