# Generated by Django 5.0.3 on 2024-03-12 20:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediatheque', '0008_remove_dvd_dateemprunt_remove_dvd_disponible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunteur_dvd',
            name='dateEmprunt',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='emprunteur_dvd',
            name='disponible',
            field=models.BooleanField(null=True),
        ),
    ]
