# Generated by Django 5.0.3 on 2024-03-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediatheque', '0012_alter_livre_auteur_alter_livre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='auteur',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='livre',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
