# Generated by Django 5.0.3 on 2024-03-15 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediatheque', '0013_alter_livre_auteur_alter_livre_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprunteur_Jeu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emprunteurs', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mediatheque.emprunteur')),
                ('jeu', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mediatheque.jeudeplateau')),
            ],
        ),
    ]
