# Generated by Django 5.0.3 on 2024-03-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediatheque', '0014_emprunteur_jeu'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunteur_jeu',
            name='disponible',
            field=models.BooleanField(null=True),
        ),
    ]
